name: Dependabot auto-merge
on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          use-github-auto-merge: True
          pr-number: ${{ github.event.inputs.pr-number || github.event.pull_request.number }}
