name: "Sphinx: Render docs"

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v5
    - name: Install pandoc
      uses: pandoc/actions/setup@v1
    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt
        pip install -e .
    - name: Sphinx build
      run: |
        sphinx-build -b html docs docs/_build --keep-going
    #- name: Upload artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: html-docs
    #    path: docs/_build/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        force_orphan: true