name: Tests

on:
  push:
    branches:
      - main
      - andrej_dev
    paths-ignore:
      - 'coverage.svg'  # Prevent infinite loops when badge changes

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install -e .[dev]

      - name: Run Tests (with coverage)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        run: |
          python -m pytest --cov=onepower --cov-config=.coveragerc --durations=25

      - name: Run Tests (without coverage)
        if: matrix.os != 'ubuntu-latest' || matrix.python-version != '3.11'
        run: |
          python -m pytest --durations=25

      - name: Upload coverage data
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage


  update-badge:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          name: coverage-data
          path: .

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          file: .coverage  # explicitly tell it where the data is

      - name: Verify Changed files
        id: verify
        uses: tj-actions/verify-changed-files@v16
        with:
          files: coverage.svg

      - name: Commit and push badge
        if: steps.verify.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Updated coverage.svg [skip ci]"
          git push
